# Generated by Django 2.1.3 on 2018-12-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depatment_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_designation', models.CharField(max_length=50)),
                ('qualification_needed', models.CharField(max_length=20)),
                ('experience_needed', models.CharField(max_length=15)),
                ('joining_date', models.DateField()),
                ('last_date_to_apply', models.DateField()),
                ('salary_offered', models.CharField(max_length=20)),
                ('person_of_contact', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=12)),
                ('other_details', models.TextField(blank=True, default=None, null=True)),
                ('department', models.ManyToManyField(to='interviews.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('expected_salary', models.CharField(max_length=20)),
                ('job_designation', models.CharField(max_length=50)),
                ('qualification_needed', models.CharField(max_length=20)),
                ('experience_needed', models.CharField(max_length=15)),
                ('last_date_to_apply', models.DateField()),
                ('interview_or_test_location', models.TextField()),
                ('additional_documents', models.TextField()),
                ('additional_information', models.TextField(blank=True, default=None, null=True)),
                ('department', models.ManyToManyField(to='interviews.Department')),
            ],
        ),
    ]
